### ISSUE TITLE
Vidéo d'apprentissage des issues

### ISSUE THREAD

**Issue by AdriClout** [clessn/test_olivier#3]
Je pense que vous devriez regarder [ce vidéo](https://www.youtube.com/watch?v=WMykv2ZMyEQ) pour comprendre **l'intérêt** des issues sur GitHub!

À plus!

<img width="851" alt="Capture d'écran 2019-04-10 09 07 39" src="https://user-images.githubusercontent.com/49455681/55881181-2ebb4380-5b70-11e9-9a8a-186de0855ee8.png">

**Comment by olichose123** [comment]
Nice find! Ça vaut la peine d'explorer les options aussi!
